name: Deploy to Live Channel

on:
  push:
    branches:
      - main

jobs:
  deploy_live_website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: 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
          firebaseServiceAccount: FIREBASE_SERVICE_ACCOUNT_SA_TEST_30D4B
          projectId: sa-test-30d4b
          channelId: live
